[package]
name = "bracer"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Lokathor/bracer"
description = "Macros to help write ARM assembly"
license = "Zlib OR Apache-2.0 OR MIT"

[dependencies]
